name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.x

      - run: go test ./...
      - run: go build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: jsonsrt-${{ matrix.os }}-${{ matrix.arch}}
          path: |
            jsonsrt
            jsonsrt.exe
